#*****************************************************************************
#* File Name: makefile
#* Author: Ayush Gupta
#* Description: Make file for compiling linklist.
#*****************************************************************************/

All:linklist 
	
linklist: linklist.cpp linklist.h
	g++ linklist.cpp -o linklist 
clean:
	rm linklist

